{% set name = "bioservices" %}
{% set version = "1.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioservices-{{ version }}.tar.gz
  sha256: ac6268c6a0a5f07fd09c5dda38c9c0a98c894d21a5c473c9850768044870d2fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - beautifulsoup4
    - colorlog
    - easydev >=0.9.36
    - grequests
    - lxml
    - pandas
    - python >=3.6
    - requests
    - requests_cache
    - suds-community
    - wrapt
    - xmltodict

test:
  imports:
    - bioservices
    - bioservices.apps
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/cokelaer/bioservices
  summary: Access to Biological Web Services from Python
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
